"using strict";const QUIZ_LIST_FILE='quizzes.json';const QUESTIONS_PER_SESSION=5;const QUIZZES_PER_PAGE=6;const STORE={quizList:[],questions:[],messages:{},currentQuestion:0,score:0,asked:[],unasked:[],answered:[],};function updateScore(){$('.score').text(`${STORE.score} / ${STORE.answered.length}`);}
function correctMessage(idx){if(Object.keys(STORE.questions[idx]).includes('correctMessage')){return STORE.questions[idx].correctMessage;}
return "That's right!";}
function incorrectMessage(idx){if(Object.keys(STORE.questions[idx]).includes('incorrectMessage')){return STORE.questions[idx].incorrectMessage;}
return `Good try, but the answer is ${STORE.questions[idx].answers[STORE.questions[idx].correctAnswer]}`;}
function updateQuestionNumber(){const numQuestions=(STORE.questions.length<QUESTIONS_PER_SESSION)?STORE.questions.length:QUESTIONS_PER_SESSION;$('.question-number').text(`${STORE.currentQuestion+1} / ${numQuestions}`);}
function collapseAnswers(method="hide"){if(!(window.orientation===90||window.orientation===-90||window.innerHeight<640)){return;}
for(let i=0;i<STORE.questions[STORE.asked[STORE.currentQuestion]].answers.length;i++){if(i===STORE.questions[STORE.asked[STORE.currentQuestion]].correctAnswer){$(`button[data-answer="${i}"]`).addClass('btn-answer-correct');}else if(i===STORE.answered[STORE.currentQuestion]){$(`button[data-answer="${i}"`).addClass('btn-answer-answered');}else{if(method.localeCompare("slide")===0){$(`button[data-answer="${i}"`).slideUp();}else{$(`button[data-answer="${i}"`).addClass('no-display');}}}}
function displayQuizList(start=0,filter="",reverseOrd=false){if(start<0){start=0;}
if(start>=STORE.quizList.length){start=(reverseOrd)?STORE.quizList.length-1:STORE.quizList.length-QUIZZES_PER_PAGE;}
$('.quizlist').html('');if(filter){$('.clear-search').removeClass('no-display');$('.btn-random-quiz').addClass('no-display');let found=0;filter=filter.toLowerCase();$('.btn-quizlist-next').prop('disabled',!reverseOrd);$('.btn-quizlist-prev').prop('disabled',(reverseOrd||start===0));for(let idx=start;(reverseOrd)?idx>=0:idx<STORE.quizList.length&&found<=QUIZZES_PER_PAGE;(reverseOrd)?idx--:idx++){if(STORE.quizList[idx].name.toLowerCase().includes(filter)||STORE.quizList[idx].keywords.some(k=>{return k.includes(filter)})){if(found===QUIZZES_PER_PAGE){$(function(){return(reverseOrd)?'.btn-quizlist-prev':'.btn-quizlist-next';}).prop('disabled',false);break;}
const html=`<button data-idx="${idx}" class="btn btn-quiz">${STORE.quizList[idx].name}</button>`;(reverseOrd)?$('.quizlist').prepend(html):$('.quizlist').append(html);found++;}}}else{let lastQuiz;if(reverseOrd){lastQuiz=(start-QUIZZES_PER_PAGE+1>=0)?start-QUIZZES_PER_PAGE+1:0;}else{lastQuiz=(STORE.quizList.length>start+QUIZZES_PER_PAGE)?start+QUIZZES_PER_PAGE-1:STORE.quizList.length-1;}
$('.btn-quizlist-next').prop('disabled',start>=STORE.quizList.length-1||lastQuiz>=STORE.quizList.length-1);$('.btn-quizlist-prev').prop('disabled',start<=0||lastQuiz<=0);$('.clear-search').addClass('no-display');$('.btn-random-quiz').removeClass('no-display');for(let idx=start;(reverseOrd)?idx>=lastQuiz:idx<=lastQuiz;(reverseOrd)?idx--:idx++){const html=`<button data-idx="${idx}" class="btn btn-quiz">${STORE.quizList[idx].name}</button>`;(reverseOrd)?$('.quizlist').prepend(html):$('.quizlist').append(html);}
$('.search-quizzes').focus();}}
async function populateStartCard(){await loadQuizList();displayQuizList();}
function displayRandomUnaskedQuestion(){displayQuestion(STORE.unasked[Math.floor(Math.random()*STORE.unasked.length)]);}
function displayQuestion(num){updateQuestionNumber();updateReply();$('.question-ctr').html(`<p class="question">${STORE.questions[num].question}</p>`);const alreadyAsked=STORE.asked.includes(num);const alreadyAnswered=(alreadyAsked&&STORE.answered.length>STORE.asked.indexOf(num));if(!alreadyAsked){STORE.asked.push(num);STORE.unasked.splice(STORE.unasked.indexOf(num),1);if(STORE.unasked.length===0){for(let i=0;i<STORE.questions.length;i++){if(!STORE.asked.includes(i)){STORE.unasked.push(i);}}}}
$('.answer-list').html('');STORE.questions[num].answers.forEach(function(answer,i){$('.answer-list').append(`<button class="btn btn-answer answer" data-answer=${i}>${answer}</button>`);});$('.btn-prev').prop('disabled',(STORE.currentQuestion===0));$('.btn-next').prop('disabled',!alreadyAnswered);$('.btn-submit-answer').prop('disabled',alreadyAnswered);if(alreadyAnswered){const ans=STORE.answered[STORE.currentQuestion];$('.answer-list').find('button').prop('disabled',true);collapseAnswers();$(`button[data-answer="${ans}"]`).addClass('btn-answer-answered');$(`button[data-answer="${STORE.questions[STORE.asked[STORE.currentQuestion]].correctAnswer}"]`).addClass('btn-answer-correct');$('.answer-reply').slideDown();$('.btn-next').focus();}else{$('.answer-reply').slideUp();}
$('.question').focus();}
function resultMessage(pct){let message;if(pct>=1){if(STORE.messages.hasOwnProperty('perfect')){message=STORE.messages.perfect;}else{message="Perfect!"};}else if(pct>=0.8){if(STORE.messages.hasOwnProperty('great')){message=STORE.messages.great;}else{message="Great Job!"}}else if(pct>=0.6){if(STORE.messages.hasOwnProperty('good')){message=STORE.messages.good;}else{message="Good Job!"}}else if(pct>=0.4){if(STORE.messages.hasOwnProperty('bad')){message=STORE.messages.bad;}else{message="Keep Trying!"}}else{if(STORE.messages.hasOwnProperty('terrible')){message=STORE.messages.terrible;}else{message="Better Luck Next Time!"}}
return message;}
function displayEndCard(){$('.card-question').slideUp();$('.card-answers').slideUp();$('.card-score').slideUp();const numberQuestions=(STORE.questions.length<QUESTIONS_PER_SESSION)?STORE.questions.length:QUESTIONS_PER_SESSION;if(numberQuestions===0){$('.result-msg').text("Only the owl and planets quiz are currently available. Try one of those!");$('.btn-try-again').prop('disabled',true);$('.card-result').slideDown();}else{$('.btn-try-again').prop('disabled',false);$('.result-msg').text(resultMessage(STORE.score/numberQuestions));$('.card-result').slideDown();}
$('.results-msg').focus();}
function updateReply(){if(STORE.currentQuestion>=STORE.answered.length){$('.answer-reply').html(`<p></p>`);return;}
if(STORE.questions[STORE.asked[STORE.currentQuestion]].correctAnswer===STORE.answered[STORE.currentQuestion]){$('.answer-reply').html(`<p>${correctMessage(STORE.asked[STORE.currentQuestion])}</p>`);}else{$('.answer-reply').html(`<p>${incorrectMessage(STORE.asked[STORE.currentQuestion])}</p>`);}}
async function loadTheme(themeFile){let ok=true;try{await fetch(themeFile).then(response=>{if(!response.ok)ok=false;});}catch(e){return;}
if(!ok){return;}
$('head').append(`<link href="${themeFile}" rel="stylesheet" type="text/css" class="quiz-theme">`);}
async function loadQuiz(quiz){let response;let json;try{response=await fetch(quiz);json=await response.json();}catch(e){STORE.questions=[];STORE.messages=[];return;}
STORE.questions=json.questions;STORE.messages=json.messages;updateQuestionNumber();reset();}
async function loadQuizList(){let response;let json;try{response=await fetch(QUIZ_LIST_FILE);json=await response.json();}catch(e){STORE.quizList=null;return;}
STORE.quizList=json.quizzes;}
function reset(full=false){if(full){STORE.unasked.splice(0,STORE.unasked.length);STORE.questions.splice(0,STORE.questions.length);}else{if(STORE.unasked.length===0){for(let i=0;i<STORE.questions.length;i++){STORE.unasked.push(i);}}}
STORE.asked.splice(0,STORE.asked.length);STORE.answered.splice(0,STORE.answered.length);STORE.score=0;STORE.currentQuestion=0;}
function searchQuizListSubmit(){return false;}
function main(){populateStartCard();$(nextQuestionHandler);$(previousQuestionHandler);$(tryAgainHandler);$(restartHandler);$(submitHandler);$(quizHandler);$(searchQuizListHandler);$(searchQuizListSubmitHandler);$(nextQuizPageHandler);$(previousQuizPageHandler);$(clearSearchHandler);}
function previousQuestionHandler(){$('.btn-prev').click(function(event){event.stopPropagation();STORE.currentQuestion--;displayQuestion(STORE.asked[STORE.currentQuestion]);$('.btn-submit-answer').prop('disabled',true);$('.btn-next').prop('disabled',false);});}
function quizHandler(){$('.card-search').on('click','.btn-quiz',async function(event){let quiz=$(this).data('idx');if(quiz==='random'){quiz=Math.floor(Math.random()*STORE.quizList.length);}
loadTheme(STORE.quizList[quiz].theme);await loadQuiz(STORE.quizList[quiz].quiz);$('head').find('title').text(`${STORE.quizList[quiz].name} Quiz`);if(!STORE.questions||STORE.questions.length===0){$('header').find('h1').text('Error loading quiz');$('.final-score').addClass('no-display');$('.card-search').slideUp();displayEndCard();return;}
$('header').find('h1').text(`${STORE.quizList[quiz].name} Quiz`);$('.card-search').slideUp();$('.card-score').slideDown();$('.card-question').slideDown();$('.card-answers').slideDown();displayRandomUnaskedQuestion();})}
function submitHandler(){$('.card-answers').on('click','.answer',function(event){event.stopPropagation();event.preventDefault();const answer=Number($(this).data('answer'));if(answer===NaN||answer===undefined){return;}
STORE.answered.push(answer);updateReply();if(answer===STORE.questions[STORE.asked[STORE.currentQuestion]].correctAnswer){STORE.score++;}
updateScore();$('.btn-next').prop('disabled',false);$('button.answer').prop('disabled',true);;$(`button[data-answer="${STORE.answered[STORE.currentQuestion]}`).addClass('btn-answer-answered');$(`button[data-answer="${STORE.questions[STORE.asked[STORE.currentQuestion]].correctAnswer}"]`).addClass('btn-answer-correct');collapseAnswers();$('.answer-reply').slideDown();$('.btn-next').focus();});}
function nextQuestionHandler(){$('.card-answers').on('click','.btn-next',function(event){event.stopPropagation();STORE.currentQuestion++;const numberQuestions=(STORE.questions.length<QUESTIONS_PER_SESSION)?STORE.questions.length:QUESTIONS_PER_SESSION;if(STORE.answered.length===numberQuestions){displayEndCard();}else if(STORE.currentQuestion<STORE.asked.length){displayQuestion(STORE.asked[STORE.currentQuestion]);}else{displayRandomUnaskedQuestion();}});}
function tryAgainHandler(){$('.btn-try-again').click(function(event){reset();displayRandomUnaskedQuestion();$('.card-result').slideUp();$('.card-question').slideDown();$('.card-answers').slideDown();$('.card-score').slideDown();updateScore();updateQuestionNumber();});}
function restartHandler(){$('.btn-restart').click(function(event){reset(true);$('.card-result').slideUp();$('.search-quizzes').val('');displayQuizList();$('.card-search').slideDown();updateScore();$('.question-number').text('_ / _');$('head').find('title').text('What Is... Trivia?');$('header').find('h1').text('What Is... Trivia?');$('head').find('link[class="quiz-theme"]').remove();});}
function searchQuizListHandler(){$('.search-quizzes').on('input',function(event){displayQuizList(0,$('.search-quizzes').val());});}
function searchQuizListSubmitHandler(){$('.search-quizzes').on('keydown',function(event){if(event.keyCode===13){event.stopPropagation();event.preventDefault();}
if(event.keyCode===27){event.stopPropagation();event.preventDefault();$('.search-quizzes').val('');displayQuizList();}});}
function nextQuizPageHandler(){$('.btn-quizlist-next').click(function(event){displayQuizList(Number($('.btn-quiz:last-child').data('idx'))+1,$('.search-quizzes').val());});}
function previousQuizPageHandler(){$('.btn-quizlist-prev').click(function(event){displayQuizList(Number($('.btn-quiz:first-child').data('idx'))-1,$('.search-quizzes').val(),true);});}
function clearSearchHandler(){$('.clear-search').click(function(event){$('.search-quizzes').val('');displayQuizList();})}
$(document).ready(function(){main();});